version: "3.8"

services:
  api:
    build:
      context: .
    image: "pdfrenderer-api"
    ports:
    - "8080:8080"
    env_file:
    - .env
    depends_on:
    - db
    volumes:
    - ./vol-images:/app/images
  db:
    image: postgres:14.1
    volumes:
    - pdf-renderer_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pdfrenderer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"

volumes:
  pdf-renderer_pgdata:
    external: true
