version: "3.8"

services:
  api:
    build:
      context: .
    image: pdfrenderer
    ports:
    - "8080:8080"
    env_file:
    - .env
    depends_on:
    - db
    - rabbit
    volumes:
    - ./vol-images:/app/images
    - ./vol-documents:/app/documents
  db:
    image: postgres:14.1
    volumes:
    - pdf-renderer_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pdfrenderer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
  rabbit:
    image: rabbitmq:3.9
    env_file:
    - .env
  workers:
    image: pdfrenderer
    command: dramatiq src.messaging.tasks -p 2 -t 4
    env_file:
    - .env
    depends_on:
    - rabbit
    restart: unless-stopped
    volumes:
    - ./vol-images:/app/images
    - ./vol-documents:/app/documents

volumes:
  pdf-renderer_pgdata:
    external: true
